//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoCode.PicaFlor.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamoCode.PicaFlor.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta aplicación usa los datos de la RestAPI del proyecto Colibrí. 
        ///
        ///También usa el sistema MvvmCross de Stuart Logde. 
        ///
        ///Se trata de un proyecto completamente libre que puedes descargar desde github.
        ///
        ///El nombre de la aplicación, PicaFlor, es otra manera de dirigirse al ave que da nombre a este proyecto..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre....
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error con la conexión con el servidor, vuelva a intentarlo más tarde.
        /// </summary>
        public static string ConectError {
            get {
                return ResourceManager.GetString("ConectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congresistas.
        /// </summary>
        public static string Congresistas {
            get {
                return ResourceManager.GetString("Congresistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas son sus últimas votaciones.
        /// </summary>
        public static string LastVotes {
            get {
                return ResourceManager.GetString("LastVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hemos podido localizar el termino.
        /// </summary>
        public static string NoLocalized {
            get {
                return ResourceManager.GetString("NoLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En estos momentos no hay servicio de conexión disponible.
        /// </summary>
        public static string NoNetworkData {
            get {
                return ResourceManager.GetString("NoNetworkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidos.
        /// </summary>
        public static string Partidos {
            get {
                return ResourceManager.GetString("Partidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Votaciones.
        /// </summary>
        public static string SesionDetailVotaciones {
            get {
                return ResourceManager.GetString("SesionDetailVotaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesiones.
        /// </summary>
        public static string Sesiones {
            get {
                return ResourceManager.GetString("Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abstenciones.
        /// </summary>
        public static string SesionesDetailAbstencion {
            get {
                return ResourceManager.GetString("SesionesDetailAbstencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En contra.
        /// </summary>
        public static string SesionesDetailContra {
            get {
                return ResourceManager.GetString("SesionesDetailContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string SesionFecha {
            get {
                return ResourceManager.GetString("SesionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº sesiones.
        /// </summary>
        public static string SesionNumeroSesiones {
            get {
                return ResourceManager.GetString("SesionNumeroSesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A favor.
        /// </summary>
        public static string SessionesDetailFavor {
            get {
                return ResourceManager.GetString("SessionesDetailFavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voto.
        /// </summary>
        public static string Voto {
            get {
                return ResourceManager.GetString("Voto", resourceCulture);
            }
        }
    }
}
